version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@3.2.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: main
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          repo: 'next13-on-ecs'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}'
          path: .
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: 'service:${AWS_RESOURCE_NAME_PREFIX}'
          cluster: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
          container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}'
