version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
jobs:
  build_and_push_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: 'zenn-app-frontend'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}'
          path: .
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only: main
