version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@3.2.0

# jobs:
#   build_and_push_image:
#     machine:
#       image: ubuntu-2204:2022.10.2
#     steps:
#       - checkout
#       - aws-ecr/build-and-push-image:

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: main
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          repo: 'next13-on-ecs'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}'
          path: .

      # - aws-ecs/deploy-service-update:
      #   requires:
      #     - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
      #   family: '${AWS_RESOURCE_NAME_PREFIX}'
      #   service-name: '${AWS_RESOURCE_NAME_PREFIX}-service'
      #   cluster: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
